version: "3.8"
services:
  rag_api:
    container_name: rag_api
    build:
      context: ./rag-nodejs-api
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./uploads/:/app/src/uploads
    networks:
      - rag_default
