version: "3.7"
services:
  rag_api:
    container_name: rag_api
    build:
      context: ./rag-nodejs-api
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./uploads/:/app/src/uploads
    networks:
      - rag_default

  rag_ollama:
    container_name: rag_ollama
    image: ollama/ollama
    volumes:
      - .data/.ollama:/root/.ollama
    networks:
      - rag_default
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
networks:
    rag_default:
        name: rag_default